// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvAXMbKc8pOJptX-ws-JUBGAFo_vITA48',
    appId: '1:41236700093:web:f567ac39d25771986c90d4',
    messagingSenderId: '41236700093',
    projectId: 'ai-plants-app',
    authDomain: 'ai-plants-app.firebaseapp.com',
    storageBucket: 'ai-plants-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTRg1OrtvMPRTfW0WA-pnoskowOAzU2Q',
    appId: '1:41236700093:android:c0fbf7a77f8064556c90d4',
    messagingSenderId: '41236700093',
    projectId: 'ai-plants-app',
    storageBucket: 'ai-plants-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaIk0RyY1MR0_nzA9-_SeweaoE1-dv2JY',
    appId: '1:41236700093:ios:795a96982e77e1be6c90d4',
    messagingSenderId: '41236700093',
    projectId: 'ai-plants-app',
    storageBucket: 'ai-plants-app.appspot.com',
    iosBundleId: 'com.example.plantsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaIk0RyY1MR0_nzA9-_SeweaoE1-dv2JY',
    appId: '1:41236700093:ios:79b1430cb2ea623e6c90d4',
    messagingSenderId: '41236700093',
    projectId: 'ai-plants-app',
    storageBucket: 'ai-plants-app.appspot.com',
    iosBundleId: 'com.example.plantsApp.RunnerTests',
  );
}
